### PR TITLE
added templates for ISMIR 2022

### PR DESCRIPTION
**Pull request by nkundiushuti**

### CODE REVIEW

**Comment by ajaysmurthy** [comment]
Could you please remove .gitignore file from the commit and squash all commits into one (optional)?

**Comment by nkundiushuti** [comment]
I have squashed all commits in a single commit but this is not reflected on origin

**Comment by nkundiushuti** [comment]
done!

**Comment by ajaysmurthy** [comment]
ISMIR templates for 2022

**Pull request merged**
