### PR TITLE
Lbd2024 fix

### PR DESCRIPTION
**Pull request by cwu307**
Here's the list of things I did in this PR:
1 ) fixed the missing watermark from the word template (clarification: the watermark was first introduced in 2022; in the update from Feb 2024, the watermark was absent. In the update from May 2024, the watermark was reintroduced. In the recent update, it was absent again; this PR tried to address the issue by bringing it back). 
2) added alt-text to the figure in the word template
3) make sure all the alt-text (both latex and word) is "ISMIR 2024 LBD template test image"
4) fixed the [?, ?, ?] in the compiled pdf 
5) (temporarily) removed `\DocumentMetadata{testphase={phase-III,math}}` for it seemed to cause some issues when I complied the latex locally.

### CODE REVIEW

**Comment by cwu307** [comment]
@MCMcCallum @ajaysmurthy , FYI

**Comment by MCMcCallum** [comment]
Thanks @cwu307 , could you please clarify a few things:

* Commit cf698ea states "add alt-text to the word template", yet alt-text was already present in this template and I'm struggling to see where it was missing. Was there an image there without alt-text? It'd be good to know if some alt-text was missed there, in case I have missed that in other templates.
* Commit 7f0ceb4 indicates that the lbd template did not compile locally for you. Can you provide more context here? What was your environment and tools for attempting to compile it? What errors were you seeing? I tested it with TexLive 2023 (in overleaf) and 2024 (locally), but it'd be good to know any issues that may exist with other configurations.
* Commit dcc148b states that the missing watermark issue was caused by the latest update. However, this watermark was not present prior to the latest update and did not change in the latest update. Could you please clarify that this was not a regression in the most recent alt-text update as you have suggested.

**Comment by cwu307** [comment]
Thanks for the quick response @MCMcCallum ! 

1) I first replaced the word template with the one that contains the LBD watermark. This commit was to "add alt-text" to this previous template. Apologies for the confusion! 
2) yes, I used MacTeX.pkg (https://tug.org/mactex/mactex-download.html) and compiled using an editor (Texmaker 5.1.4). I am on MacOS 14.5! 
3) in your PR from Feb, the watermark was not there; this could be due to the fact that 2023 LBD template accidentally dropped the watermark (introduced in 2022). I added the watermark back in my previous PR in May. I am guess you might have overwritten with your old file? 

Edit:
2) the error messages: 
> ! Package tagpdf Error: The number of automatic begin (48) and end (47)(tagpdf) text-unit para hooks differ!For immediate help type H <return>.... \end{document}
3) I will update my descriptions and add more context.

**Comment by MCMcCallum** [comment]
Gotcha!

1) Understood! Thanks for fixing this watermark.
2) If we are seeing issues with a modern MacTex version (was your version 2024 or 2023 or prior?), perhaps we should remove this line from both the LBD and regular submission templates to be safe. Based on your error, it may be a tagpdf package version issue. I updated this package prior to testing compiling locally.
3) Ah, I was comparing 2024v1 to 2024v2, but now I understand there was a "v1.5" in between. I suspect this was a merging issue between forks. Thanks for clarifying.

**Comment by cwu307** [comment]
2) I am using the 2024 version; I manually updated the package `tagpdf` and compiled again --> still getting the same error. Maybe it is safer to remove the line for now?

3) no problem at all! Thanks for taking a look!

Edit: I also copied the files to Overleaf and compiled there (TeX live version 2024). When I selected "stop on first error", I can reproduce the same error message on Overleaf. I need to select "try to compile despite errors" in order to proceed.  I think it's safer to remove this line.

**Comment by MCMcCallum** [comment]
I agree. Seeing this PR is already open, would you mind removing this line from the `ISMIR2024_template.tex` file also?

Unfortunately this will mean that the alt-text in latex templates won't work with screen readers, but it appears the latex distributions are just not quite there yet (hoping for 2025!)

**Comment by cwu307** [comment]
No problem at all. Just updated the PR! I noticed that the original pdf file also had [?, ?, ?] so I updated it as well. 

🙏

**Comment by ajaysmurthy** [comment]
Is the PR good to merge with the changes?

**Comment by cwu307** [comment]
Yeah, I think it's good to go, unless there is any additional change that @MCMcCallum would like me to address?

**Pull request merged**
