### PR TITLE
[Merge] TISMIR Template

### PR DESCRIPTION
**Pull request by stefan-balke**
Templates for the TISMIR journal.

Joint effort with @franrodalg

### CODE REVIEW

**Comment by stefan-balke** [comment]
By looking at the examples from other journals issued by the same publisher, I think we can do some further tweaking.

https://www.psychologicabelgica.com/articles/10.5334/pb.372/

E.g.: 
* Horizontal Lines
* Non-serif font
* header (also good for arxiv preprints)

**Comment by franrodalg** [comment]
That is a very good idea. I have checked a few journals by the publisher, and most seem quite different from the Word template we used as reference, though. For starters, to the best of my knowledge, most are single column. Apart form _Psychologica Belgica_, [_International Review of Social Psychology_](https://www.rips-irsp.com/) also features double column. In both cases, however, sections are __unnumbered__. 

Shall we assume unnumbered sections in TISMIR as well? That is quite an important decision for the template, I think.

**Comment by stefan-balke** [comment]
I think sections will stay numbered as in the Word template but I we should propose something and then let the editorial board decide. However, this is already something one can extend. Let's see.

**Review by stefan-balke — COMMENTED** [review]
lgtm

**Comment by stefan-balke** [comment]
Hey @ejhumphrey,

please merge this thing. We gonna have some updates as soon as authors start to use this but the board is fine with it so far.

Thanks
Stefan

**Comment by stefan-balke** [comment]
Pinging @ejhumphrey or @ismirweb – shouldn't make a difference :)

**Comment by stefan-balke** [comment]
thanks!

**Pull request merged**
